# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geek & Tech Girls
email: geek.and.tech.girls@gmail.com
description: Comunidad que a través del Software Libre acerca la tecnología a mujeres de todas las edades, a la vez que lucha por una sociedad igualitaria e inclusiva.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://geekandtechgirls.github.io" # the base hostname & protocol for your site
twitter_username: geekandtechgirl
github_username:  geekandtechgirls
facebook_username: geekandtechgirl

# Build settings
markdown: kramdown
