title: Geek & Tech Girls
description: > # this means to ignore newlines until "baseurl:"
  Comunidad que a través del Software Libre acerca la tecnología a mujeres de todas las edades, a la vez que lucha por una sociedad igualitaria e inclusiva.
permalink: ':title/'
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Geek & Tech Girls # add your name
author-img: 1w.jpg # add your photo
twitter: geekandtechgirl # add your Twitter handle
github: geekandtechgirls # add your Github handle
facebook: geekandtechgirl
email: geek.and.tech.girls@gmail.com # add your Email address
telegram: geekandtechgirls

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 4
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "vendor"]
